### ISSUE TITLE
Does not work: docker-entrypoint-initdb.d

### ISSUE THREAD

**Issue by NickolyMarques** [GlassOfWhiskey/docker-liferay-workspace-example#2]
Hello, 

I´ll trying create a liferay workspace with your example (with the last version liferay), everything is fine, but in docker-compose the part "docker-entrypoint-initdb.d" does not run :( , I´m using mysql 5:7, cause with de last liferay 7.1 does not starting. Can you helpe me, about both? 

Thank you very much.

**Comment by GlassOfWhiskey** [comment]
Hi Nickoly,
sorry for the delay but I've been really busy the last days :(
Did you solve your issue?
Regarding MySQL, there is a significant ap between 5.x and 8.x releases, therefore many things could work in a totally different way. I didn't get a good look at it for now, so I can't help you beyond that :(

**Comment by NickolyMarques** [comment]
Hi, 

I closed, cause I got make run the docker-entrypoint-initdb.d", but with the MySql 5.7 version. 

With the MySql 8.x (like in your video) doesn't work :( 

So any way, thanks! :)

Best regards!
